/*

 File generated by ../../tools/rozofsstorage_netdata_cfg.py from rozofsstorage_netdata_cfg.input

 Copyright (c) 2010 Fizians SAS. <http://www.fizians.com>
 This file is part of Rozofs.

 Rozofs is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation, version 2.

 Rozofs is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see
 <http://www.gnu.org/licenses/>.
 */
#ifndef _ROZOFSSTORAGE_NETDATA_CFG_H
#define _ROZOFSSTORAGE_NETDATA_CFG_H

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <libconfig.h>
#include <unistd.h>
#include <inttypes.h>
#include <sys/types.h>
#include <dirent.h>
void rozofsstorage_netdata_cfg_read(char * fname);

int rozofsstorage_netdata_cfg_does_file_exist(char * fname);
uint64_t rozofsstorage_netdata_cfg_get_mtime(char * fname);

/*_______________________________
** ENUM definion
*/

/*_______________________________
** rozofsstorage_netdata_cfg structure
*/
typedef struct _rozofsstorage_netdata_cfg_t {

  /*
  ** global scope configuration parameters
  */

  // Whether to display counts graph
  int32_t     display_count;
  // Whether to display duration graph
  int32_t     display_duration;
  // Whether to display bytes graph
  int32_t     display_bytes;
  // Whether to display bytes graph
  int32_t     debug;

  /*
  ** count scope configuration parameters
  */

  // Count to display
  int32_t     display_count_read;
  int32_t     display_count_write;
  int32_t     display_count_truncate;
  int32_t     display_count_rebuild_start;
  int32_t     display_count_write_empty;
  int32_t     display_count_stat;
  int32_t     display_count_remove;

  /*
  ** duration scope configuration parameters
  */

  // duration to display
  int32_t     display_duration_read;
  int32_t     display_duration_write;
  int32_t     display_duration_truncate;
  int32_t     display_duration_write_empty;
  int32_t     display_duration_stat;
  int32_t     display_duration_remove;

  /*
  ** bytes scope configuration parameters
  */

  // Bytes to display
  int32_t     display_bytes_read;
  int32_t     display_bytes_write;
} rozofsstorage_netdata_cfg_t;

extern rozofsstorage_netdata_cfg_t rozofsstorage_netdata_cfg;

/*_______________________________
** ENUM macro
*/
#endif
