#ifndef __ROZOFS_RBS_ERROR_E2String_h__
#define __ROZOFS_RBS_ERROR_E2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Wednesday 2018 February 14, 08:56:31
   Command line : 
 ../../tools/enum2String.py -n ROZOFS_RBS_ERROR_E -f storage.h -c 17

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list ROZOFS_RBS_ERROR_E
 *
 * @param x : value from ROZOFS_RBS_ERROR_E to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * ROZOFS_RBS_ERROR_E2String (const ROZOFS_RBS_ERROR_E x) {
  switch(x) {
    case rozofs_rbs_error_none                   : return("none");
    case rozofs_rbs_error_no_such_cluster        : return("no such cluster");
    case rozofs_rbs_error_not_enough_storages_up : return("not enough storages up");
    case rozofs_rbs_error_file_deleted           : return("file deleted");
    case rozofs_rbs_error_file_to_much_running_rebuild: return("file to much running rebuild");
    case rozofs_rbs_error_rebuild_start_failed   : return("rebuild start failed");
    case rozofs_rbs_error_read_error             : return("read error");
    case rozofs_rbs_error_transform_error        : return("transform error");
    case rozofs_rbs_error_rebuild_broken         : return("rebuild broken");
    case rozofs_rbs_error_write_failed           : return("write failed");
    case rozofs_rbs_error_not_enough_projection_read: return("not enough projection read");
    case rozofs_rbs_error_no_spare_target_available: return("no spare target available");
    case rozofs_rbs_error_unknown                : return("unknown");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

