#ifndef __storio_trc_service_e2String_h__
#define __storio_trc_service_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Thursday 2019 October 31, 10:45:27
   Command line : 
 ../../tools/enum2String.py -n storio_trc_service_e -f storio_trc.h -c 19

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list storio_trc_service_e
 *
 * @param x : value from storio_trc_service_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * storio_trc_service_e2String (const storio_trc_service_e x) {
  switch(x) {
    case storio_trc_service_tcp_rd               : return("tcp rd");
    case storio_trc_service_local_rd             : return("local rd");
    case storio_trc_service_rdma_rd              : return("rdma rd");
    case storio_trc_service_tcp_wr               : return("tcp wr");
    case storio_trc_service_local_wr             : return("local wr");
    case storio_trc_service_rdma_wr              : return("rdma wr");
    case storio_trc_service_tcp_wr_empty         : return("tcp wr empty");
    case storio_trc_service_trunc                : return("trunc");
    case storio_trc_service_rb_start             : return("rb start");
    case storio_trc_service_rb_stop              : return("rb stop");
    case storio_trc_service_remove               : return("remove");
    case storio_trc_service_rm_chunk             : return("rm chunk");
    case storio_trc_service_repair               : return("repair");
    case storio_trc_service_rdma_setup           : return("rdma setup");
    case storio_trc_service_local_setup          : return("local setup");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

