#ifndef __storage_device_kpi_e2String_h__
#define __storage_device_kpi_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Tuesday 2019 November 05, 10:11:25
   Command line : 
 ../../tools/enum2String.py -n storage_device_kpi_e -f storage_device_kpi.h -c 19

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list storage_device_kpi_e
 *
 * @param x : value from storage_device_kpi_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * storage_device_kpi_e2String (const storage_device_kpi_e x) {
  switch(x) {
    case storage_device_kpi_read                 : return("read");
    case storage_device_kpi_write                : return("write");
    case storage_device_kpi_max                  : return("max");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

