#ifndef __storage_device_status_e2String_h__
#define __storage_device_status_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Wednesday 2018 February 14, 08:56:41
   Command line : 
 ../../tools/enum2String.py -n storage_device_status_e -f storage.h -U -c 22

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list storage_device_status_e
 *
 * @param x : value from storage_device_status_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * storage_device_status_e2String (const storage_device_status_e x) {
  switch(x) {
    case storage_device_status_none              : return("NONE");
    case storage_device_status_init              : return("INIT");
    case storage_device_status_is                : return("IS");
    case storage_device_status_rebuild           : return("REBUILD");
    case storage_device_status_reloc             : return("RELOC");
    case storage_device_status_resec             : return("RESEC");
    case storage_device_status_failed            : return("FAILED");
    case storage_device_status_oos               : return("OOS");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

