#ifndef __rozofs_file_distribution_rule_e2String_h__
#define __rozofs_file_distribution_rule_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Wednesday 2018 February 14, 16:30:47
   Command line : 
 ../tools/enum2String.py -n rozofs_file_distribution_rule_e -f rozofs.h -c 25

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list rozofs_file_distribution_rule_e
 *
 * @param x : value from rozofs_file_distribution_rule_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * rozofs_file_distribution_rule_e2String (const rozofs_file_distribution_rule_e x) {
  switch(x) {
    case rozofs_file_distribution_size_balancing : return("size balancing");
    case rozofs_file_distribution_weigthed_round_robin: return("weigthed round robin");
    case rozofs_file_distribution_strict_round_robin_forward: return("strict round robin forward");
    case rozofs_file_distribution_strict_round_robin_inverse: return("strict round robin inverse");
    case rozofs_file_distribution_read_round_robin: return("read round robin");
    case rozofs_file_distribution_max            : return("max");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

