#ifndef __rozofs_device_distribution_rule_e2String_h__
#define __rozofs_device_distribution_rule_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Wednesday 2018 October 10, 14:48:16
   Command line : 
 ../tools/enum2String.py -n rozofs_device_distribution_rule_e -f rozofs.h -c 32

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list rozofs_device_distribution_rule_e
 *
 * @param x : value from rozofs_device_distribution_rule_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * rozofs_device_distribution_rule_e2String (const rozofs_device_distribution_rule_e x) {
  switch(x) {
    case rozofs_device_distribution_rule_size_balancing: return("size balancing");
    case rozofs_device_distribution_rule_write   : return("write");
    case rozofs_device_distribution_rule_read    : return("read");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

