#ifndef __rozofs_rcmd_status_e2String_h__
#define __rozofs_rcmd_status_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Thursday 2017 July 27, 15:05:56
   Command line : 
 ../../tools/enum2String.py -f rozofs_rcmd.h -n rozofs_rcmd_status_e -c 19

 ____________________________________________________________________
 */

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list rozofs_rcmd_status_e
 *
 * @param x : value from rozofs_rcmd_status_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * rozofs_rcmd_status_e2String (rozofs_rcmd_status_e x) {

  switch(x) {
    case rozofs_rcmd_status_cmd                  : return("cmd");
    case rozofs_rcmd_status_success              : return("success");
    case rozofs_rcmd_status_failed               : return("failed");
    case rozofs_rcmd_status_unexpected_command   : return("unexpected command");
    case rozofs_rcmd_status_no_connection        : return("no connection");
    case rozofs_rcmd_status_remote_disconnection : return("remote disconnection");
    case rozofs_rcmd_status_protocol_error       : return("protocol error");
    case rozofs_rcmd_status_missing_param        : return("missing param");
    case rozofs_rcmd_status_message_too_big      : return("message too big");
    case rozofs_rcmd_status_out_of_memory        : return("out of memory");
    case rozofs_rcmd_status_server_error         : return("server error");
    case rozofs_rcmd_status_local_error          : return("local error");
    case rozofs_rcmd_status_no_such_file         : return("no such file");
    case rozofs_rcmd_status_open_failure         : return("open failure");
    case rozofs_rcmd_status_read_failure         : return("read failure");
    case rozofs_rcmd_status_max                  : return("max");
    /* Unexpected value */
    default: return "??";
  }
}
#ifdef	__cplusplus
}
#endif
#endif

