.\" Process this file with
.\" groff -man -Tascii rozodiag.8
.\"
.TH ROZODIAG 8 "FEBRUARY 2015" RozoFS "User Manuals"
.SH NAME
rozodiag \- RozoFS diagnostic tool
.SH SYNOPSIS
.B rozodiag TARGET... [ OPTIONS ]
.B
.SH DESCRIPTION
.B rozodiag
is the diagnostic interface to the RozoFS processes.
.SH TARGET
.P 
 Several diagnostic targets can be specified. 
.P
.RS 
.B TARGET = [ -i <nodes> ] { -p <NPorts> | -T <LPorts> }
.RE
.P
 Each target names one or several node (-i) and their numeric (-p) or logical (-T) diagnostic ports.
 <nodes> can be a hostname or an IP address or a range or a list of hostnames or IP addresses.
 When the <nodes> is omitted in a TARGET, it takes the value of the previous TARGET. 
 When no previous target, local address 127.0.0.1 is used as <nodes>.
 At least one -p or -T option must be set.
.P
.RS 
.B <nodes> = { <hosts> | <IP@> }
.RE
.RS
.B <hosts> = { <hostname> | <hostname>:<N>-<P> | <hostname>:<N>,..,<P> }
.RE
.RS
.B <IP@> = { <a>.<b>.<c>.<N> | <a>.<b>.<c>.:<N>-<P> | <a>.<b>.<c>.:<N>,..,<P> } 
.RE
.P
 The numeric port is either one single numeric value or a list of numeric values or a range of numeric values.
.P
.RS
.B <NPorts> = { <port> | <firstPort>,..,<lastPort> | <firstPort>-<lastPort> }
.RE
.P
 The logical port is a logical naming of the destination process diagnostic port.
.P
.RS
.B <LPorts> = { 
.RE
.RS
.B | export | export:0                
(master exportd)  
.RE
.RS
.B | export:<slave>                   
(a slave exportd)
.RE
.RS
.B | export:<slave1>,..,<slaveN>      
(a list of slave exportd)
.RE
.RS
.B | export:<slave1>-<slaveN>         
(a range of slave exportd)
.RE
.RS
.B | storaged | storio:0                        
(a storaged)
.RE
.RS
.B | storio:<cid>                     
(the storio of cluster <cid>)
.RE
.RS
.B | storio:<cid1>,...,<cidN>         
(storios of a list of cluster)
.RE
.RS
.B | storio:<cid1>-<cidN>             
(storios of a range of cluster)
.RE
.RS
.B | mount:<m> | mount:<m>:0          
(a rozofsmount instance)
.RE
.RS
.B | mount:<m1>,..,<mN>               
(a list of rozofsmount instances)
.RE
.RS
.B | mount:<m1>-<mN>                  
(a range of rozofsmount instances)
.RE
.RS
.B | mount:<m>:<s>                    
(instance <s> of storcli of rozofsmount instance <m>)
.RE
.RS
.B | mount:<m>:<s1>,...<sN>           
(a list of instances of storcli of rozofsmount instance <m>)
.RE
.RS
.B | mount:<m>:<s1>-<sN>              
(a range of instances of storcli of rozofsmount instance <m>)
.RE
.RS
.B | rebalancer[:<instance>]          
(rebalancer)  
.RE
.RS
.B }
.RE         
.SH OPTIONS
.IP "-h, --help"
.RS
Print help. 
.RE
.IP "-c <cmdline>"
.RS
.I <cmdline>
is the optional diagnostic command line. Several -c options can be set
in order to run several diagnostic commands in a run. 
When neither -c nor -f is set in the command, 
the rozodiag tools connects to the target in interactive mode.
.RE
.IP "-f <cmdfile>"
.RS
.I <cmdfile> 
is a file containing a diagnostic command per file line that the
rozodiag tool will run. 
When neither -c nor -f is set in the command, 
the rozodiag tools connects to the target in interactive mode.
.RE
.IP "-period <seconds>"
.RS
.I <seconds>
gives the periodicity in seconds (floating) to run the diagnostic commands given either
through the -c or the -f option. 
.SH EXAMPLES
.P
Interrogating procedure statistics of export slave 1 on node 192.168.2.1 
.RS
rozodiag -i 192.168.2.21 -T export:1 -c profiler
.RE
.P
Getting disk statuses from the storaged of 4 nodes
.RS
rozodiag -i 192.168.2.:21-24 -T storaged -c dstatus
.RE
.P
Getting periodicaly storios throughput for the 6 clusters of one node
.RS
rozodiag -i 192.168.2.21 -T storio:1-6 -c throughput -period 30
.RE
.P
Getting the uptime of rozofsmount instance 2 and its 4 STORCLIs on 2 nodes
.RS
rozodiag -i 192.168.2.:21,23 -T mount:2:0-4 -c uptime
.RE
.P
Speed sampling of the profiler information on rozofsmount instance 2
.RS
rozodiag -i 192.168.2.21 -T mount:2 -c prof reset -period 0.1
.RE
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.SH "REPORTING BUGS"
Report bugs to <bugs@fizians.org>.
.SH COPYRIGHT
Copyright (c) 2013 Fizians SAS. <http://www.fizians.com>

RozoFS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published
by the Free Software Foundation, version 2.

RozoFS is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
.SH AUTHOR
Fizians <http://www.fizians.org>
.SH "SEE ALSO"
.BR rozofs (7),
