#!/bin/bash
#set -x
syntax() {
  "usage : ${base} <full path>"
  exit 1
}

#
# Get rozofsmount PID
#
get_pid() {
  PID=`ps -o pid,cmd -C rozofsmount | grep ${mnt} | awk '{print $1}'`
}

#
# Remove trailing /
#
remove_trailing_slash() {
  val=$1
  while [ 1 ]
  do
    last=`echo ${val} | tail -c 2`
    case "${last}" in
      "/") val=${val:0:-1};;
      *) echo ${val}; return;;
    esac
  done
}

base=`basename $0`
case "$1" in
  "") syntax;;
esac

# 
# Remove last / in the mount point
#
mnt=`remove_trailing_slash "$1"`

      
# Unmount
umount ${mnt} 2> /dev/null
sleep 2
umount -l ${mnt}  2> /dev/null
sleep 1



get_pid
# No PID => done
case "$PID" in
  "") exit 0;;
esac  

# Kill rozofsmount
kill ${PID}
sleep 1

get_pid
# No PID => done
case "$PID" in
  "") exit 0;;
esac  

# Kill rozofsmount
kill -9 ${PID}
