#!/bin/bash
# Copyright (c) 2010 Fizians SAS. <http://www.fizians.com>
# This file is part of Rozofs.
#
# Rozofs is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, version 2.
#
# Rozofs is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#set -x

#
# This script is used to moved old files of a hybrig/tiering export 
# from the fast volume toward the slow volume
MOVECMD="rozo_vmove"
#MOVECMD="/home/jean-pierre/rozoClients/mfile/tests/build/src/exportd/rozo_vmove"

#
# USAGE
#
usage() {
  if [[ ! -z "$1" ]]
  then
    printf "\n\033[1m\033[91m  !!! %s !!!\033[0m\n\n" "$1"
  fi  
  echo "rozo_aging - RozoFS utility to move the old files from the fast volume"
  echo "             toward the slow volume when in aging tiering mode."
  echo " "
  echo "usage: rozo_aging --age <#hours> <mountpoint>"
  echo "  -a, --age <#hours>  Move all files that have not been mdified within the last <#hours>."  
  echo "  <mountpoint>        This is a RozoFS mountpoint on which to move the aging files."
  exit 1
}
#
# Register parameters
#
eid=""
local="NO"
path=""
hours=""
path=${PWD}
while [ ! -z $1 ]
do
  
  #
  # Debug mode
  #
  if [ "$1" == "--debug" ]
  then
    set -x
    shift 1
    continue
  fi

  #
  # Help
  #
  if [ "$1" == "-h" ]
  then
    usage
  fi
  if [ "$1" == "--help" ]
  then
    usage
  fi
    
  #
  # local mode : use local host name as active export
  #  
  if [ "$1" == "--local" ]
  then
    local="YES"
    shift 1
    continue
  fi

  #
  # get nb hours 
  #
  if [ "$1" == "--age" ] || [ "$1" == "-a" ]
  then

    shift 1
    if [ -z $1 ]
    then
      usage "Missing hours number after --age option"
    fi
    
    if [[ $1 =~ ^[0-9]+$ ]]
    then
      hours=$1
    else
      usage " --age $1 is not a valid value"
    fi
    shift 1      
    continue 
  fi
  
  path=$1
  shift 1      
  continue 
  
done

if [[ ${hours} == "" ]]
then
  usage "Missing mandatory parameter --age"
fi  
 
#
# Find out the current RozoFS exportd from the current path
#
res=`attr -qg rozofs.export ${path} 2>/dev/null`
if [ $? -ne 0 ]
then
  usage "\"${path}\" is not a RozoFS mountpoint"
fi  
#
# This is a RozoFS mountpoint
#
exports=`echo ${res} | awk '{print $1}'`
eid=`echo ${res} | awk '{print $2}'`


# 
# Find out which of these exports is the active one using rozodiag
#
if [ "${local}" == "YES" ]
then
  active="$HOSTNAME"
else
  for active in `echo $exports | tr \/ ' '`
  do
    rozodiag -i ${active} -T export:0 -c up | grep uptime >> /dev/null
    case "$?" in
      "0") break;;
      *)   active="";;
    esac      
  done
  case "${active}" in
    "") {
      echo "Active exportd not found within ${exports}"
      exit 1
    };;
   esac   
fi


# 
# Is the current node the active export
#
if [ "$HOSTNAME" == "${active}" ]
then
  #
  # Curent node is the active export 
  #
  ${MOVECMD} --eid ${eid} --mount ${path} --slow --modified ${hours} 
else
  #
  # Forward the command to the active axport
  #
  ssh ${active} "${MOVECMD} --eid ${eid} --mount ${path} --slow --modified ${hours}"
fi
exit $?
