/*

 File generated by ../../tools/rozofsmount_netdata.py from rozofsmount_netdata.input

 Copyright (c) 2010 Fizians SAS. <http://www.fizians.com>
 This file is part of Rozofs.

 Rozofs is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation, version 2.

 Rozofs is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see
 <http://www.gnu.org/licenses/>.
 */
#ifndef _ROZOFSMOUNT_NETDATA_READ_SHOW_H
#define _ROZOFSMOUNT_NETDATA_READ_SHOW_H

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <libconfig.h>
#include <unistd.h>
#include <inttypes.h>
#include <sys/types.h>
#include <dirent.h>
/*____________________________________________________________________________________________
**
** Set a value to a common configuration parameter
** 
** @param param   Parameter name
** @param value   New value to set
** 
** @retval 1 on success, 0 else
*/
static inline int rozofsmount_netdata_generated_set(char * pChar, char *parameter, char *value) {
  if (strcmp(parameter,"display_count")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count,value);
  }
  if (strcmp(parameter,"display_duration")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_duration,value);
  }
  if (strcmp(parameter,"display_duration")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_duration,value);
  }
  if (strcmp(parameter,"display_count_lookup")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_lookup,value);
  }
  if (strcmp(parameter,"display_count_lookup_agg")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_lookup_agg,value);
  }
  if (strcmp(parameter,"display_count_forget")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_forget,value);
  }
  if (strcmp(parameter,"display_count_getattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_getattr,value);
  }
  if (strcmp(parameter,"display_count_setattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setattr,value);
  }
  if (strcmp(parameter,"display_count_readlink")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_readlink,value);
  }
  if (strcmp(parameter,"display_count_mknod")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_mknod,value);
  }
  if (strcmp(parameter,"display_count_mkdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_mkdir,value);
  }
  if (strcmp(parameter,"display_count_unlink")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_unlink,value);
  }
  if (strcmp(parameter,"display_count_rmdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_rmdir,value);
  }
  if (strcmp(parameter,"display_count_symlink")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_symlink,value);
  }
  if (strcmp(parameter,"display_count_rename")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_rename,value);
  }
  if (strcmp(parameter,"display_count_open")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_open,value);
  }
  if (strcmp(parameter,"display_count_link")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_link,value);
  }
  if (strcmp(parameter,"display_count_read")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_read,value);
  }
  if (strcmp(parameter,"display_count_write")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_write,value);
  }
  if (strcmp(parameter,"display_count_flush")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_flush,value);
  }
  if (strcmp(parameter,"display_count_release")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_release,value);
  }
  if (strcmp(parameter,"display_count_opendir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_opendir,value);
  }
  if (strcmp(parameter,"display_count_readdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_readdir,value);
  }
  if (strcmp(parameter,"display_count_releasedir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_releasedir,value);
  }
  if (strcmp(parameter,"display_count_fsyncdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_fsyncdir,value);
  }
  if (strcmp(parameter,"display_count_statfs")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_statfs,value);
  }
  if (strcmp(parameter,"display_count_setxattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setxattr,value);
  }
  if (strcmp(parameter,"display_count_getxattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_getxattr,value);
  }
  if (strcmp(parameter,"display_count_listxattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_listxattr,value);
  }
  if (strcmp(parameter,"display_count_removexattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_removexattr,value);
  }
  if (strcmp(parameter,"display_count_access")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_access,value);
  }
  if (strcmp(parameter,"display_count_create")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_create,value);
  }
  if (strcmp(parameter,"display_count_getlk")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_getlk,value);
  }
  if (strcmp(parameter,"display_count_setlk")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setlk,value);
  }
  if (strcmp(parameter,"display_count_setlk_int")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setlk_int,value);
  }
  if (strcmp(parameter,"display_count_ioctl")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_ioctl,value);
  }
  if (strcmp(parameter,"display_count_clearlkowner")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_clearlkowner,value);
  }
  if (strcmp(parameter,"display_count_lookup")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_lookup,value);
  }
  if (strcmp(parameter,"display_count_lookup_agg")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_lookup_agg,value);
  }
  if (strcmp(parameter,"display_count_forget")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_forget,value);
  }
  if (strcmp(parameter,"display_count_getattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_getattr,value);
  }
  if (strcmp(parameter,"display_count_setattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setattr,value);
  }
  if (strcmp(parameter,"display_count_readlink")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_readlink,value);
  }
  if (strcmp(parameter,"display_count_mknod")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_mknod,value);
  }
  if (strcmp(parameter,"display_count_mkdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_mkdir,value);
  }
  if (strcmp(parameter,"display_count_unlink")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_unlink,value);
  }
  if (strcmp(parameter,"display_count_rmdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_rmdir,value);
  }
  if (strcmp(parameter,"display_count_symlink")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_symlink,value);
  }
  if (strcmp(parameter,"display_count_rename")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_rename,value);
  }
  if (strcmp(parameter,"display_count_open")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_open,value);
  }
  if (strcmp(parameter,"display_count_link")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_link,value);
  }
  if (strcmp(parameter,"display_count_read")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_read,value);
  }
  if (strcmp(parameter,"display_count_write")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_write,value);
  }
  if (strcmp(parameter,"display_count_flush")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_flush,value);
  }
  if (strcmp(parameter,"display_count_release")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_release,value);
  }
  if (strcmp(parameter,"display_count_opendir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_opendir,value);
  }
  if (strcmp(parameter,"display_count_readdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_readdir,value);
  }
  if (strcmp(parameter,"display_count_releasedir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_releasedir,value);
  }
  if (strcmp(parameter,"display_count_fsyncdir")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_fsyncdir,value);
  }
  if (strcmp(parameter,"display_count_statfs")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_statfs,value);
  }
  if (strcmp(parameter,"display_count_setxattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setxattr,value);
  }
  if (strcmp(parameter,"display_count_getxattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_getxattr,value);
  }
  if (strcmp(parameter,"display_count_listxattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_listxattr,value);
  }
  if (strcmp(parameter,"display_count_removexattr")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_removexattr,value);
  }
  if (strcmp(parameter,"display_count_access")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_access,value);
  }
  if (strcmp(parameter,"display_count_create")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_create,value);
  }
  if (strcmp(parameter,"display_count_getlk")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_getlk,value);
  }
  if (strcmp(parameter,"display_count_setlk")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setlk,value);
  }
  if (strcmp(parameter,"display_count_setlk_int")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_setlk_int,value);
  }
  if (strcmp(parameter,"display_count_ioctl")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_ioctl,value);
  }
  if (strcmp(parameter,"display_count_clearlkowner")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_count_clearlkowner,value);
  }
  if (strcmp(parameter,"display_bytes_read")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_bytes_read,value);
  }
  if (strcmp(parameter,"display_bytes_write")==0) {
    ROZOFSMOUNT_NETDATA_SET_BOOL(display_bytes_write,value);
  }
  pChar += rozofs_string_append_error(pChar,"No such parameter ");
  pChar += rozofs_string_append_error(pChar,parameter);
  pChar += rozofs_eol(pChar);\
  return -1;
}
/*____________________________________________________________________________________________
**
** Search for parameters approximatively like a given string 
** 
** @param parameter   Approximative parameter name we are searching for
** 
** @retval The number of parameters matching the input string
*/
static inline int rozofsmount_netdata_generated_search(char * pChar, char *parameter) {
  int match = 0;

  if (strcasestr("display_count",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count,True);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    pChar += rozofs_string_append(pChar,"// Whether to display counts graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count,True);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_duration",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    pChar += rozofs_string_append(pChar,"// Whether to display duration graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_duration",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    pChar += rozofs_string_append(pChar,"// Whether to display bytes graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_lookup",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    pChar += rozofs_string_append(pChar,"// Count to display\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_lookup_agg",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_forget",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_getattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_readlink",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_mknod",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_mkdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_unlink",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_rmdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_symlink",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_rename",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_open",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_link",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_read",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_write",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_flush",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_release",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_opendir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_readdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_releasedir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_fsyncdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_statfs",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setxattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_getxattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_listxattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_removexattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_access",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_create",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_getlk",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setlk",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setlk_int",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_ioctl",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_clearlkowner",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_lookup",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    pChar += rozofs_string_append(pChar,"// Duration to display\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_lookup_agg",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_forget",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_getattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_readlink",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_mknod",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_mkdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_unlink",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_rmdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_symlink",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_rename",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_open",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_link",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_read",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_write",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_flush",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_release",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_opendir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_readdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_releasedir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_fsyncdir",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_statfs",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setxattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_getxattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_listxattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_removexattr",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_access",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_create",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_getlk",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setlk",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_setlk_int",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_ioctl",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_count_clearlkowner",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_bytes_read",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_read,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    pChar += rozofs_string_append(pChar,"// Bytes to display   \n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_read,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }

  if (strcasestr("display_bytes_write",parameter) != NULL) {
    match++;
    ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_write,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_write,=);
    if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  }
  if (match == 0) {
    pChar += rozofs_string_append_error(pChar,"No such parameter like ");
    pChar += rozofs_string_append_error(pChar,parameter);
    pChar += rozofs_eol(pChar);\
  }
  return match;
}
/*____________________________________________________________________________________________
**
** rozofsmount_netdata man function
**
*/
void man_rozofsmount_netdata(char * pChar) {
  pChar += rozofs_string_append_underscore(pChar,"\nUsage:\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config [long]");
  pChar += rozofs_string_append     (pChar,"\t\tdisplays the whole rozofsmount_netdata configuration.\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config [long] <scope>");
  pChar += rozofs_string_append     (pChar,"\tdisplays only the <scope> configuration part.\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config search <parameter>");
  pChar += rozofs_string_append     (pChar,"\tdisplays parameters approximatively like <parameter>.\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config reload");
  pChar += rozofs_string_append     (pChar,"\treloads and then displays the configuration.\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config set <param> <value>");
  pChar += rozofs_string_append     (pChar,"\tmodifies a configuration parameter in memory.\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config save");
  pChar += rozofs_string_append     (pChar,"\tsaves configuration from memory to disk.\n");
  pChar += rozofs_string_append_bold(pChar,"\trozofsmount_netdata_config files");
  pChar += rozofs_string_append     (pChar,"\tReturns the name of the configuration file and the saved ones.\n");
}
/*____________________________________________________________________________________________
**
** global scope configuration parameters
**
*/
char * show_rozofsmount_netdata_module_global(char * pChar) {

  pChar += rozofs_string_append_effect(pChar,"#                                                            \n#     ", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"    GLOBAL SCOPE CONFIGURATION PARAMETERS         ", ROZOFS_COLOR_YELLOW ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"     \n#                                                            \n\n", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count,True);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  pChar += rozofs_string_append(pChar,"// Whether to display counts graph\n");
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count,True);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  pChar += rozofs_string_append(pChar,"// Whether to display duration graph\n");
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  pChar += rozofs_string_append(pChar,"// Whether to display bytes graph\n");
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  return pChar;
}
/*____________________________________________________________________________________________
**
** global scope configuration parameters
**
*/
char * show_rozofsmount_netdata_module_global_short(char * pChar) {

  pChar += rozofs_string_append_effect(pChar,"#                                                            \n#     ", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"    GLOBAL SCOPE CONFIGURATION PARAMETERS         ", ROZOFS_COLOR_YELLOW ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"     \n#                                                            \n\n", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count,True);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Whether to display counts graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count,True);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Whether to display duration graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Whether to display bytes graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
  }
  return pChar;
}
/*____________________________________________________________________________________________
**
** count scope configuration parameters
**
*/
char * show_rozofsmount_netdata_module_count(char * pChar) {

  pChar += rozofs_string_append_effect(pChar,"#                                                            \n#     ", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"    COUNT SCOPE CONFIGURATION PARAMETERS          ", ROZOFS_COLOR_YELLOW ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"     \n#                                                            \n\n", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  pChar += rozofs_string_append(pChar,"// Count to display\n");
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  pChar += rozofs_string_append(pChar,"// Duration to display\n");
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_read,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  pChar += rozofs_string_append(pChar,"// Bytes to display   \n");
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_read,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_write,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_bold(pChar);
  ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_write,=);
  if (isDefaultValue==0) pChar += rozofs_string_set_default(pChar);
  return pChar;
}
/*____________________________________________________________________________________________
**
** count scope configuration parameters
**
*/
char * show_rozofsmount_netdata_module_count_short(char * pChar) {

  pChar += rozofs_string_append_effect(pChar,"#                                                            \n#     ", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"    COUNT SCOPE CONFIGURATION PARAMETERS          ", ROZOFS_COLOR_YELLOW ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);
  pChar += rozofs_string_append_effect(pChar,"     \n#                                                            \n\n", ROZOFS_COLOR_BLUE ROZOFS_COLOR_BOLD ROZOFS_COLOR_REVERSE);


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Count to display\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Duration to display\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_read,=);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Bytes to display   \n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_read,=);
  }


  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_write,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_write,=);
  }
  return pChar;
}
/*____________________________________________________________________________________________
**
** global scope configuration parameters
**
*/
char * save_rozofsmount_netdata_module_global(char * pChar) {

  pChar += rozofs_string_append(pChar,"#____________________________________________________________\n");
  pChar += rozofs_string_append(pChar,"# ");
  pChar += rozofs_string_append(pChar,"global");
  pChar += rozofs_string_append(pChar," scope configuration parameters\n");
  pChar += rozofs_string_append(pChar,"#____________________________________________________________\n\n");

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count,True);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Whether to display counts graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count,True);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Whether to display duration graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_duration,True);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Whether to display bytes graph\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_duration,True);
  }
  return pChar;
}
/*____________________________________________________________________________________________
**
** count scope configuration parameters
**
*/
char * save_rozofsmount_netdata_module_count(char * pChar) {

  pChar += rozofs_string_append(pChar,"#____________________________________________________________\n");
  pChar += rozofs_string_append(pChar,"# ");
  pChar += rozofs_string_append(pChar,"count");
  pChar += rozofs_string_append(pChar," scope configuration parameters\n");
  pChar += rozofs_string_append(pChar,"#____________________________________________________________\n\n");

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Count to display\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup,=);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Duration to display\n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_lookup_agg,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_lookup_agg,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_forget,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_forget,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readlink,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mknod,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mknod,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_mkdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_mkdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_unlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_unlink,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rmdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rmdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_symlink,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_symlink,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_rename,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_rename,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_open,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_open,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_link,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_link,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_read,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_read,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_write,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_write,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_flush,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_flush,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_release,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_release,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_opendir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_opendir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_readdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_readdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_releasedir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_releasedir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_fsyncdir,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_fsyncdir,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_statfs,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_statfs,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setxattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getxattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_listxattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_listxattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_removexattr,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_removexattr,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_access,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_access,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_create,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_create,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_getlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_getlk,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_setlk_int,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_setlk_int,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_ioctl,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_ioctl,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_count_clearlkowner,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_count_clearlkowner,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_read,=);
  if (isDefaultValue==0) {
    pChar += rozofs_string_append(pChar,"// Bytes to display   \n");
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_read,=);
  }

  ROZOFSMOUNT_NETDATA_IS_DEFAULT_BOOL(display_bytes_write,=);
  if (isDefaultValue==0) {
    ROZOFSMOUNT_NETDATA_SHOW_BOOL(display_bytes_write,=);
  }
  return pChar;
}
/*____________________________________________________________________________________________
**
** Save configuration parameter on disk
** 
** @param pChar   Parameter name
** @param value   New value to set
** 
** @retval 1 on success, 0 else
*/
static inline int rozofsmount_netdata_generated_save(char * pChar) {
  char *pBuff;
  int   fd;
  char  saved_file[256];

  /*
  ** Save previous file
  */
  time_t t = time(NULL);
  struct tm tm = *localtime(&t);
  sprintf(saved_file,"%s_%2.2d-%2.2d-%2.2d_%2.2d:%2.2d:%2.2d", rozofsmount_netdata_file_name,tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday, tm.tm_hour, tm.tm_min, tm.tm_sec);
  rename(rozofsmount_netdata_file_name,saved_file);

  /*
  ** Creat a new file
  */
  fd = open(rozofsmount_netdata_file_name,O_CREAT|O_TRUNC|O_APPEND|O_WRONLY,0777);
  if (fd < 0) {
    pChar += rozofs_string_append_error(pChar,"Can not open ");
    pChar += rozofs_string_append_error(pChar,rozofsmount_netdata_file_name);
    return -1;
  }
  pBuff = save_rozofsmount_netdata_module_global(myBigBuffer);
  if (write(fd,myBigBuffer,pBuff-myBigBuffer)<0) {
    pChar += rozofs_string_append_error(pChar,"Can not write ");
    pChar += rozofs_string_append_error(pChar,rozofsmount_netdata_file_name);
    close(fd);
    return -1;
  }
  pBuff = save_rozofsmount_netdata_module_count(myBigBuffer);
  if (write(fd,myBigBuffer,pBuff-myBigBuffer)<0) {
    pChar += rozofs_string_append_error(pChar,"Can not write ");
    pChar += rozofs_string_append_error(pChar,rozofsmount_netdata_file_name);
    close(fd);
    return -1;
  }
  pChar += rozofs_string_append(pChar,"Saved in ");
  pChar += rozofs_string_append(pChar,rozofsmount_netdata_file_name);
  pChar += rozofs_eol(pChar);
  close(fd);
  return 0;
}
/*____________________________________________________________________________________________
**
** rozofsmount_netdata diagnostic function
**
*/
char * rozofsmount_netdata_generated_show_all_files(char * pChar) {
  char            cmd[256];

  if (rozofsmount_netdata_file_is_read==0) {
    pChar += rozofs_string_append_error(pChar,"Can not read configuration file ");
    return pChar;
  }
  sprintf(cmd,"ls -lisa %s*",rozofsmount_netdata_file_name);
  uma_dbg_run_system_cmd(cmd, pChar, uma_dbg_get_buffer_len()); 
  return pChar;
}
/*____________________________________________________________________________________________
**
** rozofsmount_netdata diagnostic function
**
*/
void rozofsmount_netdata_generated_show(char * argv[], uint32_t tcpRef, void *bufRef) {
char *pChar = uma_dbg_get_buffer();
char *pHead;
int     longformat = 0;
char  * moduleName = NULL;

  if (argv[1] != NULL) {

    if (strcmp(argv[1],"reload")==0) {
      rozofsmount_netdata_read(NULL);
      pChar += rozofs_string_append(pChar, "File reloaded\n");
      uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
      return;
    }

    if (strcmp(argv[1],"set")==0) {
      if ((argv[2] == NULL)||(argv[3] == NULL)) {
        pChar += rozofs_string_append_error(pChar, "Missing <parameter> and/or <value>\n");
        uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
        return;
      }
      rozofsmount_netdata_generated_set(pChar, argv[2],argv[3]);
      uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
      return;
    }

    if (strcmp(argv[1],"search")==0) {
      if (argv[2] == NULL) {
        pChar += rozofs_string_append_error(pChar, "Missing <parameter>\n");
        uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
        return;
      }
      rozofsmount_netdata_generated_search(pChar, argv[2]);
      uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
      return;
    }

    if (strcmp(argv[1],"save")==0) {
      rozofsmount_netdata_generated_save(pChar);
      uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
      return;
    }

    if (strcmp(argv[1],"files")==0) {
      rozofsmount_netdata_generated_show_all_files(pChar);
      uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
      return;
    }

    if (strcmp(argv[1],"long")==0) {
      longformat = 1;
      moduleName = argv[2];
    }
    else {
      moduleName = argv[1];
      if (argv[2] != NULL) {
        if (strcmp(argv[2],"long")==0) {
          longformat = 1;
        }
      }
    }

    if (moduleName != NULL) {
      if (strcasecmp("global",moduleName)==0) {
        if ((pHead = (char *)ruc_buf_getPayload(bufRef)) == NULL) {
          severe( "ruc_buf_getPayload(%p)", bufRef );
          return;
        }
        /*
        ** Set the command recall string
        */
        pChar = uma_dbg_cmd_recall((UMA_MSGHEADER_S *)pHead);
        if (longformat) {
          pChar = show_rozofsmount_netdata_module_global(pChar);
        } else {
          pChar = show_rozofsmount_netdata_module_global_short(pChar);
        } 
        uma_dbg_send_buffer(tcpRef, bufRef, pChar-pHead, TRUE);
        return;
      }
      else if (strcasecmp("count",moduleName)==0) {
        if ((pHead = (char *)ruc_buf_getPayload(bufRef)) == NULL) {
          severe( "ruc_buf_getPayload(%p)", bufRef );
          return;
        }
        /*
        ** Set the command recall string
        */
        pChar = uma_dbg_cmd_recall((UMA_MSGHEADER_S *)pHead);
        if (longformat) {
          pChar = show_rozofsmount_netdata_module_count(pChar);
        } else {
          pChar = show_rozofsmount_netdata_module_count_short(pChar);
        } 
        uma_dbg_send_buffer(tcpRef, bufRef, pChar-pHead, TRUE);
        return;
      }
      else {
        pChar += rozofs_string_append_error(pChar, "Unexpected configuration scope\n");
        uma_dbg_send(tcpRef, bufRef, TRUE, uma_dbg_get_buffer());
        return;
      }
    }
  }

  if ((pHead = (char *)ruc_buf_getPayload(bufRef)) == NULL) {
    severe( "ruc_buf_getPayload(%p)", bufRef );
    return;
  }
  /*
  ** Set the command recall string
  */
  pChar = uma_dbg_cmd_recall((UMA_MSGHEADER_S *)pHead);
  if (rozofsmount_netdata_file_is_read==0) {
    pChar += rozofs_string_append_error(pChar,"Can not read configuration file ");
  }
  
  
  if (longformat) {
    pChar = show_rozofsmount_netdata_module_global(pChar);
  } else {
    pChar = show_rozofsmount_netdata_module_global_short(pChar);
  } 
  uma_dbg_send_buffer(tcpRef, bufRef, pChar-pHead, FALSE);
  
  bufRef = uma_dbg_get_new_buffer(tcpRef);
  if (bufRef == NULL) {
    warning( "uma_dbg_get_new_buffer() Buffer depletion");
    return;
  }
  if ((pHead = (char *)ruc_buf_getPayload(bufRef)) == NULL) {
    severe( "ruc_buf_getPayload(%p)", bufRef );
    return;
  }
  pChar = pHead+sizeof(UMA_MSGHEADER_S);
  *pChar = 0;
  
  if (longformat) {
    pChar = show_rozofsmount_netdata_module_count(pChar);
  } else {
    pChar = show_rozofsmount_netdata_module_count_short(pChar);
  } 
  uma_dbg_send_buffer(tcpRef, bufRef, pChar-pHead, FALSE);
  
  bufRef = uma_dbg_get_new_buffer(tcpRef);
  if (bufRef == NULL) {
    warning( "uma_dbg_get_new_buffer() Buffer depletion");
    return;
  }
  if ((pHead = (char *)ruc_buf_getPayload(bufRef)) == NULL) {
    severe( "ruc_buf_getPayload(%p)", bufRef );
    return;
  }
  pChar = pHead+sizeof(UMA_MSGHEADER_S);
  *pChar = 0;
  pChar += rozofs_string_append(pChar,"#____________________________________________________________\n");
  pChar += rozofs_string_append(pChar,"# ");
  pChar += rozofs_string_append(pChar," rozofsmount_netdata file is ");
  pChar += rozofs_string_append(pChar,rozofsmount_netdata_file_name);
  pChar += rozofs_string_append(pChar,"\n#____________________________________________________________\n\n");
  uma_dbg_send_buffer(tcpRef, bufRef, pChar-pHead, TRUE);
  return;
}
/*____________________________________________________________________________________________
**
** Check the presence of the configuration file
** 
** @param fname   Configuration file of NULL (use default)
**
** @retval  0 if it exist, -1 else
*/
int rozofsmount_netdata_does_file_exist(char * fname) {

  if (fname == NULL) {
    strcpy(rozofsmount_netdata_file_name,ROZOFS_CONFIG_DIR"/rozofsmount_netdata.conf");
  }
  else {
    strcpy(rozofsmount_netdata_file_name,fname); 
  } 

  if (access(rozofsmount_netdata_file_name,R_OK)!=0) {
    return -1;
  }
  return 0;
}

/*____________________________________________________________________________________________
**
** Read the configuration file
*/
static inline void rozofsmount_netdata_generated_read(char * fname) {
  config_t          cfg; 

  if (rozofsmount_netdata_file_is_read == 0) {
    uma_dbg_addTopicAndMan("rozofsmount_netdata_config",show_rozofsmount_netdata, man_rozofsmount_netdata, 0);
  }

  if (rozofsmount_netdata_does_file_exist(fname) != 0) {
    printf("cant access %s: %s.", rozofsmount_netdata_file_name, strerror(errno));
    fatal("cant access %s: %s.", rozofsmount_netdata_file_name, strerror(errno));
  }

  config_init(&cfg);
  rozofsmount_netdata_file_is_read = 1;
  if (config_read_file(&cfg, rozofsmount_netdata_file_name) == CONFIG_FALSE) {
    if (errno == ENOENT) {
      info("Missing file %s.", rozofsmount_netdata_file_name);
    }
    else {
      severe("cant read %s: %s (line %d).", rozofsmount_netdata_file_name, config_error_text(&cfg),config_error_line(&cfg));
    }
    rozofsmount_netdata_file_is_read = 0;
  }

  /*
  ** global scope configuration parameters
  */
  // Whether to display counts graph 
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count,True);
  // Whether to display duration graph 
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_duration,True);
  // Whether to display bytes graph 
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_duration,True);
  /*
  ** count scope configuration parameters
  */
  // Count to display 
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_lookup,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_lookup_agg,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_forget,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_getattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_readlink,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_mknod,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_mkdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_unlink,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_rmdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_symlink,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_rename,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_open,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_link,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_read,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_write,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_flush,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_release,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_opendir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_readdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_releasedir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_fsyncdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_statfs,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setxattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_getxattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_listxattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_removexattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_access,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_create,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_getlk,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setlk,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setlk_int,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_ioctl,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_clearlkowner,=);
  // Duration to display 
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_lookup,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_lookup_agg,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_forget,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_getattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_readlink,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_mknod,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_mkdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_unlink,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_rmdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_symlink,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_rename,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_open,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_link,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_read,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_write,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_flush,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_release,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_opendir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_readdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_releasedir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_fsyncdir,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_statfs,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setxattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_getxattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_listxattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_removexattr,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_access,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_create,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_getlk,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setlk,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_setlk_int,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_ioctl,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_count_clearlkowner,=);
  // Bytes to display    
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_bytes_read,=);
  ROZOFSMOUNT_NETDATA_READ_BOOL(display_bytes_write,=);
 
  config_destroy(&cfg);
}
#endif
