#!/bin/bash
RED='\033[91m\033[40m\033[1m'
GREEN='\033[92m\033[40m'
NORMAL='\033[0m'
#_________________________________________
# Display Syntax
#_________________________________________
#
syntax() {
  echo "rozo_core all             List core files on all nodes n1, n2, ..."
  echo "rozo_core ls              List local core files"
  echo "rozo_core rm [corefile]   Remove local core file(s)"
  echo "rozo_core gdb [corefile]  Launch gdb on core file(s)"
  echo "rozo_core uptime          Get uptime of all nodes n1, n2, ..."
  exit 0
}
#_________________________________________
# List core files
#_________________________________________
#
rozo_core_ls () {

  nb=0
  for corefile in `ls /var/run/rozofs/core/*/* 2>/dev/null`
  do
  
    if [ "${nb}" == "0" ];
    then
      printf ${RED}"Some core files on ${HOSTNAME} :\n"${NORMAL}
    fi
    nb=$((nb+1))
       
    ls -lisa ${corefile}
  done

  if [ "${nb}" == "0" ];
  then
    printf ${GREEN}"No core files on ${HOSTNAME}\n"${NORMAL}
  fi
  
  exit 0
}
#_________________________________________
# Get nodes uptime
#_________________________________________
#
rozo_core_uptime () {
  case "$1" in
    "") FILTER="n";;
    *)  FILTER=$1;;
  esac
  HOSTLIST=`grep -oP "${FILTER}\d+$" /etc/hosts | sort -u`
  case "${HOSTLIST}" in
    "") {
      cat /etc/hosts
      printf "\033[91m\033[40mNo host matching prefix \"%s\" in /etc/hosts.\n" ${FILTER}
      printf "Try other prefix \"rozo_core all <prefix>\".\033[0m\n"
      exit 1
    };;
  esac  

  for h in ${HOSTLIST}
  do
    res=`ssh -o ConnectTimeout=5 ${h} "uptime"`
    warning=`echo ${res} | awk '{print $3}'`
    case "${warning}" in 
     0|1|2|3|4|5) printf "\033[91m\033[40m";;
    esac
    printf "%s : %s\033[0m\n" ${h} "${res}"
  done
  exit 0
}
#_________________________________________
# List core files on all hosts
#_________________________________________
#
rozo_core_all () {
  case "$1" in
    "") FILTER="n";;
    *)  FILTER=$1;;
  esac
  HOSTLIST=`grep -oP "${FILTER}\d+$" /etc/hosts | sort -u`
  case "${HOSTLIST}" in
    "") {
      cat /etc/hosts
      printf "\033[91m\033[40mNo host matching prefix \"%s\" in /etc/hosts.\n" ${FILTER}
      printf "Try other prefix \"rozo_core all <prefix>\".\033[0m\n"
      exit 1
    };;
  esac  
  for h in ${HOSTLIST}
  do
    ssh -o ConnectTimeout=5 ${h} "rozo_core ls"
  done
  exit 0
}

#_________________________________________
# Translate directory name to executable name
#_________________________________________
#
rozo_core_exe () {
  module=`echo $1 | awk -F'/' '{print $6;}'`
  case "${module}" in
    "export_slave") module="exportd";;
  esac  
}
#_________________________________________
# Launch gdb on core files
#_________________________________________
#
rozo_core_gdb () {

  which gdb
  if [ $? -ne "0" ];
  then
    echo "No gdb on this server.";
    exit 1
  fi  
  
  case "$1" in
    ""){
      for corefile in `ls /var/run/rozofs/core/*/* 2>/dev/null`
      do
        rozo_core_exe ${corefile}
        gdb ${module} -c ${corefile}
      done
    };;
    *) {
      rozo_core_exe $1
      gdb ${module} -c $1
    };;
  esac
  exit 0
}
#_________________________________________
# Remove core files
#_________________________________________
#
rozo_core_rm () {

  case "$1" in
    ""){
      for corefile in `ls /var/run/rozofs/core/*/* 2>/dev/null`
      do
        rm -f ${corefile}
      done
    };;
    *) {
        rm -f $1
    };;
  esac
    
  exit 0
}
#_________________________________________
# MAIN
#_________________________________________
#
case "$1" in
  ls|rm|gdb|all|uptime) rozo_core_$1 $2;;
esac
syntax  
