#ifndef __rozofs_scan_scope_e2String_h__
#define __rozofs_scan_scope_e2String_h__
#ifdef __cplusplus
extern "C" {
#endif /*__cplusplus*/
#include <strings.h>

/*___________________________________________________________________
 
   Generated by enum2String.py 
   Date : Tuesday 2019 November 26, 13:40:16
   Command line : 
 ../../tools/enum2String.py -n rozofs_scan_scope_e -f rozo_scan_by_criteria.c -c 18

  ____________________________________________________________________
*/

/*_________________________________________________________________
 * Builds a string from an integer value supposed to be within
 * the enumerated list rozofs_scan_scope_e
 *
 * @param x : value from rozofs_scan_scope_e to translate into a string
 *
 * The input value is translated into a string deduced from the enum
 * definition. When the input value do not fit any of the predefined
 * values, "??" is returned
 *
 * @return A char pointer to the constant string or "??"
 *_________________________________________________________________*/ 
static inline char * rozofs_scan_scope_e2String (const rozofs_scan_scope_e x) {
  switch(x) {
    case rozofs_scan_scope_regular_file          : return("regular file");
    case rozofs_scan_scope_symbolic_link         : return("symbolic link");
    case rozofs_scan_scope_directory             : return("directory");
    case rozofs_scan_scope_junk_file             : return("junk file");
    /* Unexpected value */
    default: return "??";
  }
}

#ifdef	__cplusplus
}
#endif
#endif

